Repository 2Jo-Logistics-Management/smart-logistics-front, pull requests merged in 2023-09, with the labels that each got.

#28 Item/item managements
  frontend/src/axios/item/ItemInsertAxios.js
  frontend/src/axios/item/ItemModifyAxios.js
  frontend/src/index.js
  frontend/src/layouts/full/sidebar/MenuItems.js
  frontend/src/redux/reducer.js
  frontend/src/redux/slices/ItemsReducer.js
  frontend/src/redux/slices/selectedItemsReducer.js
  frontend/src/redux/thunks/fetchItemsFromApi.js
  frontend/src/redux/thunks/fetchSearchItemsFromApi.js
  frontend/src/routes/Router.js
  frontend/src/views/dashboard/components/ItemsComponents.js
  frontend/src/views/dashboard/components/modal/item/ItemInsertModal.js
  frontend/src/views/dashboard/components/modal/item/ItemModifyModal.js
Labels: feat

#27 Member/check
  frontend/package.json
  frontend/src/components/shared/DashboardCard.js
  frontend/src/layouts/full/header/Header.js
  frontend/src/redux/reducer.js
  frontend/src/redux/slices/loginResponseReducer.js
  frontend/src/redux/thunks/loginResponse.js
  frontend/src/views/authentication/auth/AuthLogin.js
  frontend/src/views/dashboard/Dashboard.js
  frontend/src/views/dashboard/components/AccountComponents.js
  frontend/src/views/dashboard/components/MemberComponents.js
  frontend/src/views/dashboard/components/MonthlyEarnings.js
  frontend/src/views/dashboard/components/SalesOverview.js
  frontend/src/views/dashboard/components/StateOverviewComponents.js
  frontend/src/views/dashboard/components/YearlyBreakup.js
Labels: feat

#38 Refactor/item managements
  frontend/src/axios/item/ItemInsertAxios.js
  frontend/src/loading.js
  frontend/src/redux/slices/ItemsReducer.js
  frontend/src/views/dashboard/components/ItemsComponents.js
  frontend/src/views/dashboard/components/modal/item/ItemModifyModal.js
Labels: refactor

#41 Common/refactor
  frontend/src/layouts/full/header/Header.js
  frontend/src/routes/Router.js
  frontend/src/views/dashboard/components/AccountComponents.js
  frontend/src/views/dashboard/components/AccountComponents2.js
  frontend/src/views/dashboard/components/MemberComponents.js
  frontend/src/views/dashboard/components/MemberComponents2.js
Labels: fix

#49 Receive/refactory detail
  frontend/src/views/dashboard/components/ReceiveComponents.js
  frontend/src/views/dashboard/components/ReceiveComponents2.js
  frontend/src/views/dashboard/components/modal/ReceiveModal.js
Labels: fix

#51 fix: 페이징처리, 화면단구성 Component2지우기 #23
  frontend/src/views/dashboard/components/AccountComponents.js
  frontend/src/views/dashboard/components/AccountComponents2.js
  frontend/src/views/dashboard/components/MemberComponents.js
  frontend/src/views/dashboard/components/MemberComponents2.js
Labels: refactor

#55 fix: 피드백 받은 사항 수정완료 #54
  frontend/src/layouts/full/header/Header.js
  frontend/src/redux/slices/loginResponseReducer.js
  frontend/src/views/dashboard/components/AccountComponents.js
  frontend/src/views/dashboard/components/MemberComponents.js
Labels: fix
